version: "2"
services:
# NGINX container with startup parameters, volumes\links\port exposing
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    links:
      - api1:api1
      - api2:api2
      - api3:api3
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf:/etc/nginx/sites-enabled/site.conf:ro
      - ./nginx/ssl/domain.crt:/etc/nginx/ssl/domain.crt:ro
      - ./nginx/ssl/domain.key:/etc/nginx/ssl/domain.key:ro
      - ./nginx/logs:/var/log/nginx:rw
# First Backend with Test app
  api1:
    build: ./api1
# Second Backend with Test app
  api2:
    build: ./api2
# Third Backend with Test app
  api3:
    build: ./api3